package mods.simple.main;

import java.util.Arrays;

import mods.common.server.CommonProxy;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

	@Mod(modid = "MainCore:Simple",name="MainCore_Simple",version= "1.0.0",dependencies="required-after:Forge@[9.11.1.953,)")
	
	public class MainCoreS{
		
		
		@Instance("MainCoreS")
		public static MainCoreS instance;
	
		public static CommonProxy proxy;
	
		public String actualMCVersion="1.7.2";
	
		public MainCoreS() 
		{
		
		}
		
		@Mod.EventHandler
		public void preInit(FMLPreInitializationEvent event) 
		{
	    	ModMetadata meta = event.getModMetadata();
			meta.autogenerated = false;
			meta.credits = "(C) Roborave, 2013-2014";
			meta.authorList = Arrays.asList("Roborave");
			meta.name = "MainCore_Simple";
			meta.version ="1.0.0";
			meta.modId="MainCore:Simple";
			meta.description = "This the core for all my mods. simple version"+" 1.0.0";
		}
		
		@Mod.EventHandler
		public static void load(FMLInitializationEvent event)
		{
		
		}
	
	}
